env:
  browser: true
  es6: true
  node: true
extends: 'config'
parserOptions:
  sourceType: module
rules:
  indent:
    - error
    - tab
    -
      SwitchCase: 1
  linebreak-style:
    - error
    - unix
  quotes:
    - error
    - double
  semi:
    - error
    - always
  space-before-blocks:
    - error